version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:5000"
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - backend
      - redis

networks:
  app-network:
    driver: bridge
